export const THEMES = {
  dark: {
    label: 'Dark',
    icon: '🌑',
    vars: {
      '--bg':          '#0d1117',
      '--bg2':         '#161b22',
      '--bg3':         '#21262d',
      '--bg4':         '#2d333b',
      '--border':      '#30363d',
      '--border2':     '#444c56',
      '--text':        '#c9d1d9',
      '--text-dim':    '#8b949e',
      '--text-mid':    '#adbac7',
      '--accent':      '#58a6ff',
      '--accent2':     '#1f6feb',
      '--accent-glow': 'rgba(88,166,255,0.2)',
      '--green':       '#3fb950',
      '--yellow':      '#d29922',
      '--red':         '#f85149',
      '--orange':      '#e3b341',
      '--purple':      '#bc8cff',
      '--active':      '#3fb950',
      '--active-bg':   'rgba(63,185,80,0.1)',
      '--active-glow': 'rgba(63,185,80,0.2)',
      '--ready':       '#d29922',
      '--ready-bg':    'rgba(210,153,34,0.1)',
      '--learning':    '#58a6ff',
      '--learning-bg': 'rgba(88,166,255,0.1)',
      '--cat-utility':     '#58a6ff',
      '--cat-creation':    '#bc8cff',
      '--cat-planning':    '#3fb950',
      '--cat-development': '#e3b341',
      '--font-ui':   '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      '--font-mono': '"Courier New", Consolas, monospace',
    },
  },

  synthwave: {
    label: 'Synthwave',
    icon: '🌌',
    vars: {
      '--bg':          '#08090f',
      '--bg2':         '#0f1017',
      '--bg3':         '#181a24',
      '--bg4':         '#1e2030',
      '--border':      '#1e2030',
      '--border2':     '#2a2d3e',
      '--text':        '#e2e4f0',
      '--text-dim':    '#6b7280',
      '--text-mid':    '#9ca3af',
      '--accent':      '#7c6af7',
      '--accent2':     '#6055d4',
      '--accent-glow': 'rgba(124,106,247,0.25)',
      '--green':       '#22c55e',
      '--yellow':      '#f59e0b',
      '--red':         '#ef4444',
      '--orange':      '#f97316',
      '--purple':      '#a78bfa',
      '--active':      '#22c55e',
      '--active-bg':   'rgba(34,197,94,0.1)',
      '--active-glow': 'rgba(34,197,94,0.2)',
      '--ready':       '#f59e0b',
      '--ready-bg':    'rgba(245,158,11,0.1)',
      '--learning':    '#3b82f6',
      '--learning-bg': 'rgba(59,130,246,0.1)',
      '--cat-utility':     '#7c6af7',
      '--cat-creation':    '#ec4899',
      '--cat-planning':    '#06b6d4',
      '--cat-development': '#10b981',
      '--font-ui':   '-apple-system, BlinkMacSystemFont, "Inter", "Segoe UI", sans-serif',
      '--font-mono': '"Courier New", Consolas, monospace',
    },
  },

  light: {
    label: 'Light',
    icon: '☀️',
    vars: {
      '--bg':          '#ffffff',
      '--bg2':         '#f6f8fa',
      '--bg3':         '#eaeef2',
      '--bg4':         '#d0d7de',
      '--border':      '#d0d7de',
      '--border2':     '#b3bcc5',
      '--text':        '#24292f',
      '--text-dim':    '#57606a',
      '--text-mid':    '#424a53',
      '--accent':      '#0969da',
      '--accent2':     '#0550ae',
      '--accent-glow': 'rgba(9,105,218,0.15)',
      '--green':       '#1a7f37',
      '--yellow':      '#9a6700',
      '--red':         '#cf222e',
      '--orange':      '#bc4c00',
      '--purple':      '#8250df',
      '--active':      '#1a7f37',
      '--active-bg':   'rgba(26,127,55,0.1)',
      '--active-glow': 'rgba(26,127,55,0.15)',
      '--ready':       '#9a6700',
      '--ready-bg':    'rgba(154,103,0,0.1)',
      '--learning':    '#0969da',
      '--learning-bg': 'rgba(9,105,218,0.1)',
      '--cat-utility':     '#0969da',
      '--cat-creation':    '#8250df',
      '--cat-planning':    '#0969da',
      '--cat-development': '#1a7f37',
      '--font-ui':   '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      '--font-mono': '"Courier New", Consolas, monospace',
    },
  },

  terminal: {
    label: 'Terminal',
    icon: '💚',
    vars: {
      '--bg':          '#000000',
      '--bg2':         '#0a0a0a',
      '--bg3':         '#111111',
      '--bg4':         '#1a1a1a',
      '--border':      '#1f3d1f',
      '--border2':     '#2d5a2d',
      '--text':        '#00ff41',
      '--text-dim':    '#007a1f',
      '--text-mid':    '#00cc33',
      '--accent':      '#00ff41',
      '--accent2':     '#00cc33',
      '--accent-glow': 'rgba(0,255,65,0.2)',
      '--green':       '#00ff41',
      '--yellow':      '#ffff00',
      '--red':         '#ff0040',
      '--orange':      '#ff8c00',
      '--purple':      '#bf00ff',
      '--active':      '#00ff41',
      '--active-bg':   'rgba(0,255,65,0.08)',
      '--active-glow': 'rgba(0,255,65,0.25)',
      '--ready':       '#ffff00',
      '--ready-bg':    'rgba(255,255,0,0.08)',
      '--learning':    '#00ffff',
      '--learning-bg': 'rgba(0,255,255,0.08)',
      '--cat-utility':     '#00ff41',
      '--cat-creation':    '#00ffff',
      '--cat-planning':    '#ffff00',
      '--cat-development': '#ff8c00',
      '--font-ui':   '"Courier New", Consolas, monospace',
      '--font-mono': '"Courier New", Consolas, monospace',
    },
  },
}

const STORAGE_KEY = 'skills-agent-theme'

export function getStoredTheme() {
  return localStorage.getItem(STORAGE_KEY) || 'dark'
}

export function applyTheme(themeKey) {
  const theme = THEMES[themeKey]
  if (!theme) return
  const root = document.documentElement
  Object.entries(theme.vars).forEach(([k, v]) => root.style.setProperty(k, v))
  // Set body font explicitly
  document.body.style.fontFamily = theme.vars['--font-ui']
  localStorage.setItem(STORAGE_KEY, themeKey)
}
